name: Publish Docker Image to Docker Hub

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: https://login.docker.com/u/login/identifier?state=hKFo2SBnbUphQWlQYXpyRGJHS1BORjRuU0phcXByajVsRVlxX6Fur3VuaXZlcnNhbC1sb2dpbqN0aWTZIGxkTWthOTVad3VLLS1VYU5SSURhWG5yS0g5WWNRNFJno2NpZNkgbHZlOUdHbDhKdFNVcm5lUTFFVnVDMGxiakhkaTluYjk
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/karthik_docker

      - name: Docker Push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/karthik_docker
